### ISSUE TITLE
How to add game icons?

### ISSUE THREAD

**Issue by SlyAceZeta** [voidel/playstation-discord-status#1]
This isn't an "issue" per se but I'm not entirely sure how to go about A) adding icons to the client provided by the code as default, or B) setting up my own client and adding icons to support the games. Reading through the code and the readme I don't really see anything obvious. Could this be cleared up a bit?

**Comment by voidel** [comment]
@Azekthi I touched on it briefly but I can certainly expand the readme in the next few days on how to do this in detail. Thanks for the interest.

**Comment by SlyAceZeta** [comment]
No need to thank me! Thank _you_ for providing a working solution that's relatively easy to set up. Other projects haven't worked, hence my interest in this one 😊

**Comment by SlyAceZeta** [comment]
Ah well, [never mind...](https://discord.com/blog/playstation-discord-account-connection-linking-game-status)
